spring:
  application:
    name: tributacore-api

  datasource:
    url: jdbc:postgresql://localhost:5432/nfe
    username: nfe
    password: nfe
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

tributacore:
  storage:
    result-path: ./results
  limits:
    max-zip-size-mb: 100
    max-xml-size-mb: 10
  ncm:
    json-path: Tabela_NCM_Vigente_20260127.json
    force-reload: false

logging:
  level:
    root: INFO
    com.tributacore.api: DEBUG
    org.hibernate.SQL: WARN
